### ISSUE TITLE
Crash: "runtime error: slice bounds out of range [24:0]" on Kernel 5.8.0-41-generic

### ISSUE THREAD

**Issue by taktv6** [paultag/go-modprobe#2]
Hi,

I'm experiencing trouble using go-modprobe:
```panic: runtime error: slice bounds out of range [24:0]

goroutine 1 [running]:
pault.ag/go/modprobe.Name(0xc000584018, 0x4c, 0x0, 0x0, 0xc000584018)
        /home/takt/ACME/git/src/pault.ag/go/modprobe/elf.go:121 +0x39f
pault.ag/go/modprobe.elfMap.func1(0xc00022f860, 0x4c, 0x519fe0, 0xc000264340, 0x0, 0x0, 0x0, 0x0)
        /home/takt/ACME/git/src/pault.ag/go/modprobe/elf.go:82 +0xcc
path/filepath.walk(0xc00022f860, 0x4c, 0x519fe0, 0xc000264340, 0xc000113e48, 0x0, 0x0)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:360 +0x423
path/filepath.walk(0xc0002983c0, 0x3b, 0x519fe0, 0xc000264270, 0xc000113e48, 0x0, 0x0)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc000298080, 0x34, 0x519fe0, 0xc000264000, 0xc000113e48, 0x0, 0x0)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc00028a330, 0x2f, 0x519fe0, 0xc0003701a0, 0xc000113e48, 0x0, 0x0)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc0001640f0, 0x24, 0x519fe0, 0xc00011ab60, 0xc000113e48, 0x0, 0x0)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc000160000, 0x1d, 0x519fe0, 0xc00011a8f0, 0xc000113e48, 0x0, 0xc000120e08)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:384 +0x2fe
path/filepath.Walk(0xc000160000, 0x1d, 0xc000120e48, 0x31203831206e614a, 0x2033323a32353a37)
        /home/takt/software/go1.15.7/src/path/filepath/path.go:406 +0x105
pault.ag/go/modprobe.elfMap(0xc000160000, 0x1d, 0x0, 0x0, 0x0)
        /home/takt/ACME/git/src/pault.ag/go/modprobe/elf.go:71 +0x6a
pault.ag/go/modprobe.generateMap(...)
        /home/takt/ACME/git/src/pault.ag/go/modprobe/elf.go:63
pault.ag/go/modprobe.ResolveName(0x4f6d72, 0xd, 0x0, 0x4f6884, 0xc, 0xc000136010)
        /home/takt/ACME/git/src/pault.ag/go/modprobe/elf.go:46 +0x3d
pault.ag/go/modprobe.Load(0x4f6d72, 0xd, 0x0, 0x0, 0x4d42e0, 0xc000114058)
        /home/takt/ACME/git/src/pault.ag/go/modprobe/load.go:12 +0x3f
main.main()
        /home/takt/ACME/git/src/local/modprobe/modprobe.go:14 +0x3e
```

Here's the code I'm running to reproduce the issue:
```
package main

import (
	"pault.ag/go/modprobe"
)

const (
	MPLS_IP_TUNNEL_MODULE = "mpls_iptunnel"
)

func main() {
	err := modprobe.Load(MPLS_IP_TUNNEL_MODULE, "")
	if err != nil {
		panic(err)
	}
}
```

The problem exists on Kernel 5.8.0-41-generic.
Version 5.4.77 and lower all work fine.

**Comment by paultag** [comment]
Hurm, thanks for this report @taktv6!

I'm not able to reproduce on a system running `5.10.0` -  but I did just check in a commit that does a bounds check. This will at least avoid a panic :)

I'd love more information on how to reproduce this -- I think I could construct a crasher, but I'm interested if it's a renamed field, or something else. I'm going to leave this issue open, but hopefully your panic is resolved now, and merely an error.

Sorry I missed this, my email has been a shitshow.

**Comment by taktv6** [comment]
Hi,

just checked again with version v0.1.2 and it didn't panic.

Thanks!

**Comment by paultag** [comment]
Awesome, thanks!
